### ISSUE TITLE
Configuration for long reads?

### ISSUE THREAD

**Issue by MartinaFernandez** [Zymo-Research/miqScore16SPublic#3]
Hi, how can I run the docker image to allow Long Nanopore reads? I tried 

-e MODE=LONG

But the tool searchs for PE Illumina reads.

Thank you!

**Comment by michael-weinstein** [comment]
Let me check in on this.  I have gotten this to work on long-reads before, but it's been a while.  Can you show me your error messages?

**Comment by markus-soma** [comment]
Hi @michael-weinstein,

I am experiencing similar issues as @MartinaFernandez.
We get the following error:

```
Unable to find expected file for environment variable parameter forwardReads at /data/input/sequence/standard_submitted_R1.fastq
Traceback (most recent call last):
  File "/opt/miqscore16s/analyzeStandardReads.py", line 408, in <module>
    parameters = getApplicationParameters()
  File "/opt/miqscore16s/analyzeStandardReads.py", line 13, in getApplicationParameters
    parameters.addParameter("forwardReads", str, default = default.forwardReads, expectedFile=True)
  File "/opt/miqscore16s/miqScore16SPublicSupport/parameters/environmentParameterParser.py", line 393, in addParameter
    parameter = EnvVariable(name, typeRequirement, default, flag, validationList, lowerBound, upperBound, expectedFile, createdFile, expectedDirectory, createdDirectory, logLevel, required, externalValidation)
  File "/opt/miqscore16s/miqScore16SPublicSupport/parameters/environmentParameterParser.py", line 52, in __init__
    self.runValidations()
  File "/opt/miqscore16s/miqScore16SPublicSupport/parameters/environmentParameterParser.py", line 85, in runValidations
    self.validateExpectedFilePath()
  File "/opt/miqscore16s/miqScore16SPublicSupport/parameters/environmentParameterParser.py", line 121, in validateExpectedFilePath
    raise FileNotFoundError("Unable to find expected file %s" %self.value)
FileNotFoundError: Unable to find expected file /data/input/sequence/standard_submitted_R1.fastq
```

How can we run this tool on our Nanopore reads?
Thanks!
