### ISSUE TITLE
unspecfic error when running the program

### ISSUE THREAD

**Issue by pmenzel** [Zymo-Research/miqScore16SPublic#4]
Hi,

I build the docker container and run it on 2x251bp MiSeq reads of the V3-V4 amplicon using the command
```
docker container run -v /home/ptr/temp/miq:/data -e SAMPLENAME=211015_I249 -e FORWARDPRIMERLENGTH=21 -e REVERSEPRIMERLENGTH=21 -e AMPLICONLENGTH=450 miqscore16s
```

and get the following error:

```
Traceback (most recent call last):
  File "/opt/miqscore16s/analyzeStandardReads.py", line 410, in <module>
    dada2Outputs = runDada2Functions(parameters.forwardReads.value, parameters.reverseReads.value)
  File "/opt/miqscore16s/analyzeStandardReads.py", line 298, in runDada2Functions
    trimParameters = getTrimmingParametersWithFigaro(readFolder)
  File "/opt/miqscore16s/analyzeStandardReads.py", line 154, in getTrimmingParametersWithFigaro
    resultTable, forwardCurve, reverseCurve = Figaro.figaro.runAnalysis(sequenceFolder, parameters.ampliconLength.value, parameters.forwardPrimerLength.value, parameters.reversePrimerLength.value, parameters.minOverlap.value, parameters.fileNamingStandard.value, parameters.trimParameterDownsample.value, parameters.trimParameterPercentile.value)
  File "/opt/miqscore16s/Figaro/figaro.py", line 196, in runAnalysis
    resultTable, forwardCurve, reverseCurve = figaroSupport.trimParameterPrediction.performAnalysisLite(inputDirectory, ampliconLength + minimumOverlap, subsample=subsample, percentile=percentile, forwardPrimerLength=forwardPrimerLength, reversePrimerLength=reversePrimerLength, namingStandardAlias=fileNamingStandard)
  File "/opt/miqscore16s/Figaro/figaroSupport/trimParameterPrediction.py", line 443, in performAnalysisLite
    resultTable = runTrimParameterTestLite(forwardExpectedErrorMatrix, reverseExpectedErrorMatrix, trimPositions, minimumTrimmingPositions, forwardCurve, reverseCurve, forwardPrimerLength, reversePrimerLength)
  File "/opt/miqscore16s/Figaro/figaroSupport/trimParameterPrediction.py", line 340, in runTrimParameterTestLite
    forwardExpectedErrors = forwardExpectedErrorMatrix[forwardTrimPosition - forwardMinimumTrimPosition]
IndexError: index -1 is out of bounds for axis 0 with size 0

```
The log file in the output-folder is empty.

I already filtered the fastq files to only include reads with length 251 to get past the length check.

Further, I needed to reduce the `AMPLICONLENGTH` option to 450, otherwise I would get
```
Combined read lengths are less than the required combined length.
Combined read lengths are less than the required combined length.
```

best,
Peter

**Comment by michael-weinstein** [comment]
Sorry, forgot to respond to this sooner.  For the amplicon length, are you including the lengths of the primers in that?  If not, I believe you should be.  I think the amplicon length with the primer lengths you gave is having issues because there isn't enough overlap to analyze.
